const initialAdvent = [
  { id: 1, item: 'CD Deine Lakaien Dual', day: 1 },
  { id: 2, item: 'CD Scheuber Numb', day: 2 },
  { id: 3, item: 'Sticker, Poster', day: 3 },
  { id: 4, item: 'CD Scheuber Numb', day: 4 },
  { id: 5, item: 'CD Croona: Ascend', day: 5 },
  { id: 6, item: 'Shirt DME-Radio', day: 6 },
  { id: 7, item: 'Book -- The Cure', day: 7 },
  { id: 8, item: 'CD Omnimar: Darkpop', day: 8 },
  { id: 9, item: 'Poster von Agonoize + 1 Mini-Headphone', day: 9 },
  { id: 10, item: 'Konzertkarte Aesthetic Perfection', day: 10 },
  { id: 11, item: 'Meet&Greet mit Lord of the Lost', day: 11 },
  { id: 12, item: 'CD Burn von Burn', day: 12 },
  { id: 13, item: 'CD 25 Years VNV-Nation', day: 13 },
  { id: 14, item: 'CD Best of Mera Luna', day: 14 },
  { id: 15, item: 'Kalender 2022 Rammstein', day: 15 },
  { id: 16, item: 'Kulturtasche von Culture Kültür', day: 16 },
  { id: 17, item: 'Lene Lovich T-Shirt', day: 17 },
  { id: 18, item: 'Umhängetasche Ministry', day: 18 },
  { id: 19, item: 'Schnürsenkel von Orange Sector + EP', day: 19 },
  { id: 20, item: '3 Best of Electro Sampler', day: 20 },
  { id: 21, item: 'Kopfkissen mit DME-Logo', day: 21 },
  { id: 22, item: 'CD Digital Energy + Button', day: 22 },
  { id: 23, item: 'CD Best of 80ths Wave', day: 23 },
  { id: 24, item: 'Backstage-Pass Rammstein', day: 24 },
];

export default initialAdvent;
