const initialAdvent = [
  { id: 1, item: 'CD Deine Lakaien Dual', day: '1' },
  { id: 2, item: 'CD Scheuber Numb', day: '2' },
  { id: 3, item: 'Sticker, Poster', day: '3' },
  { id: 4, item: 'CD Scheuber Numb', day: '4' },
  { id: 5 },
  { id: 6 },
  { id: 7 },
  { id: 8 },
  { id: 9 },
  { id: 10 },
  { id: 11 },
  { id: 12 },
  { id: 13 },
  { id: 14 },
  { id: 15 },
  { id: 16 },
  { id: 17 },
  { id: 18 },
  { id: 19 },
  { id: 20 },
  { id: 21, day: 21 },
  { id: 22, day: 21 },
  { id: 23 },
  { id: 24 },
];

export default initialAdvent;
